### ISSUE TITLE
offer similar features as Rack::Protection

### ISSUE THREAD

**Issue by garu** [robrwo/Plack-Middleware-Security-Simple#4]
Hi there! First of all, thank you so much for making such a nice and useful distribution.

I was wondering if you would consider extending it to provide the same features as Ruby's [Rack::Protection](https://github.com/sinatra/sinatra/tree/master/rack-protection) - aside from the current security features yours already offers.

Since Plack and Rack are somewhat similar (as are Ruby and Perl, for that matter), I believe it should be straightforward to port. There is a [very simple test suite for it](https://github.com/sinatra/sinatra/tree/master/rack-protection/spec/lib/rack/protection) that could be used to validate each feature.

If you think this would be an interesting addition to Plack::Middleware::Security::Simple, I also volunteer to write failing tests for each of Rack::Protection's features and submit them as individual PRs. But of course I'll only work on it once (and if) you greenlight it.

What do you think?

Cheers!

**Comment by robrwo** [comment]
Some of the features of Rack::Protection are handled by other packages, e.g. Plack::Middleware::BlockHeaderInjection and Plack::Middleware::CSP.

So if you can identify specific things in Rack::Protection that aren't handled by other Plack middleware but could be added here, then we can look at whether it is worth adding these features.

However, the idea of the module is to be "simple" so I think more complex features are belong in a separate package, e.g. CSP Headers.

Others, like IP Spoofing, are harder to detect. For example, the ReverseProxy middleware trusts X-Forwarded-For your reverse proxy (e.g. Apache) is supposed to set that header. So any request with that from outside will be overwritten.  One could add something to detect alternative reverse proxy headers like 'X-Real-IP' perhaps.

It's probably worth adding a discussion of other modules in the SEE ALSO section.

**Comment by robrwo** [comment]
I think it might be better to have a distribution called something like Task::Plack::Security that includes several Plack middleware security modules., with some POD that explains how to piece them all together.

**Comment by garu** [comment]
Makes sense. Thank you!
